import Head from 'next/head';

import { trpc } from '../../../trpc/trpcClient';
import { Page } from '../Page/Page';
import { ExternalPageProps } from '../../utils/declareSsrProps';
import { notifyPromise } from '../../utils/notifyPromise';

export default function DashboardPage({ ssrTime }: ExternalPageProps) {
    const { data } = trpc.example.getHello.useQuery();
    console.log(data);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Page header={<header>header</header>} ssrTime={ssrTime}>
                main
                <button
                    onClick={() => {
                        notifyPromise(Promise.resolve(1), 'copy');
                    }}
                >
                    success toast
                </button>
                <button
                    onClick={() =>
                        notifyPromise(
                            new Promise((resolve) => {
                                setTimeout(resolve, 2000);
                            }),
                            'copy',
                        )
                    }
                >
                    loading toast
                </button>
                <button
                    onClick={() => {
                        notifyPromise(
                            new Promise((_, reject) => {
                                setTimeout(reject, 0);
                            }),
                            'copy',
                        );
                    }}
                >
                    error toast
                </button>
            </Page>
        </>
    );
}
